require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "db/migrate/**/*"
    - "spec/**/*"

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "db/migrate/**/*"
