version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws
      - data-bundle:/usr/local/bundle
    links:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      EDITOR: vi
      SOMETHING: YOUR_VALUE

  web:
    <<: *app
    command: >
      sh -c "bundle install --jobs 4 &&
             bundle exec rails s -p 3000 -b '0.0.0.0'"
#            bundle exec rails webpacker:install
    ports:
      - 3000:3000

  db:
    image: mysql:8.0
    ports:
      - 3010:3306
    volumes:
      - data-db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      MYSQL_INNODB_LARGE_PREFIX: 1

  redis:
    image: redis:latest
    ports:
      - 3020:6379

volumes:
  data-bundle:
    driver: local
  data-db:
    driver: local
