version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node
        environment:
          RAILS_ENV: test
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          DATABASE_URL: mysql2://root@127.0.0.1:3306
      - image: mysql:8.0
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_CHARSET: utf8mb4
          MYSQL_COLLATION: utf8mb4_general_ci
          MYSQL_INNODB_LARGE_PREFIX: 1
    steps:
      - checkout
      - restore_cache:
          name: restore-bundle-cache
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle-install
          command: bundle install --path=vendor/bundle
      - save_cache:
          name: store-bundle-cache
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: db:migrate
          command: ./bin/rails db:create db:schema:load
      - run:
          name: rubocop
          command: bundle exec rubocop

workflows:
  version: 2.1
  run_build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - /feature\/.*/
